version: "3.9"

services:
  frontend:
    build: ./frontend
    environment:
      - VITE_API_HOST=http://localhost:5001
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./application
    environment:
      - API_KEY=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
      - EMBEDDINGS_KEY=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
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
    ports:
      - "5001:5001"
    volumes:
    - indexes-volume:/app/indexes
    - inputs-volume:/app/inputs
    - vectors-volume:/app/vectors
    depends_on:
        - redis
        - mongo

  worker:
    build: ./application
    command: celery -A app.celery worker -l INFO
    environment:
      - API_KEY=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
      - EMBEDDINGS_KEY=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
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
      - API_URL=http://backend:5001
    depends_on:
        - redis
        - mongo

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
    driver: azure_file
    driver_opts:
      share_name: vervedemo-volume  # replace with your Azure file share name
      storage_account_name: vervedemostorageaccount  # replace with your Azure storage account name
      storage_account_key: PZZ5PHzgb0m0Uk+VJshQcI8AMfcELwaPoRjI6WGS46SPm202XR2AKLcOAap7IQojXFPI2ppTPsZr+AStH/6fJg==  # replace with your Azure storage account key
  indexes_volume:
    driver: azure_file
    driver_opts:
      share_name: indexes-volume  # replace with your Azure file share name
      storage_account_name: vervedemostorageaccount  # replace with your Azure storage account name
      storage_account_key: PZZ5PHzgb0m0Uk+VJshQcI8AMfcELwaPoRjI6WGS46SPm202XR2AKLcOAap7IQojXFPI2ppTPsZr+AStH/6fJg==  # replace with your Azure storage account key
  inputs_volume:
    driver: azure_file
    driver_opts:
      share_name: inputs-volume  # replace with your Azure file share name
      storage_account_name: vervedemostorageaccount  # replace with your Azure storage account name
      storage_account_key: PZZ5PHzgb0m0Uk+VJshQcI8AMfcELwaPoRjI6WGS46SPm202XR2AKLcOAap7IQojXFPI2ppTPsZr+AStH/6fJg==  # replace with your Azure storage account key
  vectors_volume:
    driver: azure_file
    driver_opts:
      share_name: vectors-volume  # replace with your Azure file share name
      storage_account_name: vervedemostorageaccount  # replace with your Azure storage account name
      storage_account_key: PZZ5PHzgb0m0Uk+VJshQcI8AMfcELwaPoRjI6WGS46SPm202XR2AKLcOAap7IQojXFPI2ppTPsZr+AStH/6fJg==  # replace with your Azure storage account key
